# Generated by Django 3.2 on 2021-05-03 20:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, default=api.models.generate_unique_code, max_length=8),
        ),
    ]
